---
- hosts: all
  become: yes
  tasks:
    # Stop and disable Apache service
    - name: Stop and disable Apache service
      service:
        name: apache2
        state: stopped
        enabled: no

    # Remove Apache configuration directory
    - name: Remove Apache configuration directory
      file:
        path: /etc/apache2
        state: absent

    # Remove Apache log directory
    - name: Remove Apache log directory
      file:
        path: /var/log/apache2
        state: absent

    # Remove Apache package
    - name: Remove Apache package
      apt:
        name: apache2
        state: absent

    # Remove cloned GitHub repository
    - name: Remove cloned GitHub repository
      file:
        path: /home/ubuntu/ansible
        state: absent

    # Add more tasks here to remove any other resources created by the previous playbooks
